//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp_ИСиТ_2_лаба
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ИСиТ_лабыEntities : DbContext
    {
        private static ИСиТ_лабыEntities _context;
        public ИСиТ_лабыEntities()
            : base("name=ИСиТ_лабыEntities")
        {
        }
        public static ИСиТ_лабыEntities GetContext()
        {
            if (_context == null)
                _context = new ИСиТ_лабыEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<climber> climbers { get; set; }
        public virtual DbSet<expedition_groups> expedition_groups { get; set; }
        public virtual DbSet<group_members> group_members { get; set; }
        public virtual DbSet<mountain> mountains { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
