//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp_ИСиТ_2_лаба
{
    using System;
    using System.Collections.Generic;
    
    public partial class group_members
    {
        public int record_id { get; set; }
        public int group_id { get; set; }
        public int climber_id { get; set; }
    
        public virtual climber climber { get; set; }
        public virtual expedition_groups expedition_groups { get; set; }
    }
}
