//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp_ИСиТ_2_лаба
{
    using System;
    using System.Collections.Generic;
    
    public partial class mountain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mountain()
        {
            this.expedition_groups = new HashSet<expedition_groups>();
        }
    
        public int mountain_id { get; set; }
        public string mountain_name { get; set; }
        public int height { get; set; }
        public string country { get; set; }
        public string region { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<expedition_groups> expedition_groups { get; set; }
    }
}
